### ISSUE TITLE
DataConverter is (surprisingly?) used for custom search attributes

### ISSUE THREAD

**Issue by skrul** [temporalio/sdk-java#468]
## Expected Behavior

We were putting some custom serialization / deserialization in place to handle our workflow/activity arguments and noticed that the DataConverter (including our custom one). Expected behavior was that this change would only apply to the workflow/activity arguments.

## Actual Behavior

This change also applies to the to the custom search attributes that are set on the workflow options, which would cause errors when these encoded values were being sent to ElasticSearch.

The workaround we are using is to be more selective on which class types we apply the custom data converter to and we make sure that the primitive java types use the default converter. 

## Specifications

  - Version: sdk 1.0.7
  - Platform: java / temporal 1.6.3

**Comment by vitarb** [comment]
Steve, thanks for the question. Data converter is used to serialize/deserialize all parameters that need to be sent over the wire. Your work-around sounds reasonable to me, I can see why it feels a bit hacky though. Did you expect that search attributes shouldn't be encoded at all? Do you have any proposals here or did you just want to have a discussion? If it's for the discussion then perhaps we should move the topic to our [community forum](community.temporal.io/).

**Comment by mfateev** [comment]
DataConverter is pluggable. But the format of the search attribute serialization is fixed by the service. So using DataConverter (at least one provided by the user) for search attributes is not correct. We should be careful here though as it can break backwards compatibility if we just stop using the provided DC.

**Comment by skrul** [comment]
So I talked to manu a bit about this and it turns out we were doing this slightly wrong (but the basic problem remains). We had implemented a `PayloadConverter` and added it as one of the converters in the list supplied to the default data converter. What we've been advised to do is to implement our own DataConverter instead.

However, this is where things are a bit confusing as it seems that `toPayload` is used for stuff like search attributes and memo, where `toPayloads` (note the singular vs plural) is used for workflow/activity input/output. Our solution will be to use our custom serde for `toPayloads` but then delegate to the default data converter for `toPayload`.

And I agree with maxim, stuff like search attributes and memo should be passed verbatim since these values ultimately need to be indexed by ES / read by humans so encoding them would be incorrect.
